<?php

namespace BackOffice\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationsRepository extends EntityRepository
{
}
